[workspace]
members = [
    "black-box",
]
resolver = "3"

[workspace.package]
edition = "2024"
rust-version = "1.75.0"
license = "MIT OR Apache-2.0"
repository = "https://github.com/cmleinz/black-box"
